In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn import tree

In [3]:
data=pd.read_csv("data/loan_default.csv")
# handel missing valus
data.dropna(axis=0, how='any', inplace=True)
# handel duplicates
data.drop_duplicates()
data

,UserID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,RepayRate,LoanTerm,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,Default,ZakatEligible
0,I38PQUQS96,56,85994,50587,520,80,15.23,36,Bachelor's,Full-time,Divorced,Yes,Yes,Other,0,0
1,HPSK72WA7R,69,50432,124440,458,15,4.81,60,Master's,Full-time,Married,No,No,Other,0,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,21.17,24,Master's,Unemployed,Divorced,Yes,Yes,Auto,1,0
3,V2KKSFM3UN,32,31713,44799,743,0,7.07,24,High School,Full-time,Married,No,No,Business,0,0
4,EY08JDHTZP,60,20437,9139,633,8,6.51,48,Bachelor's,Unemployed,Divorced,No,Yes,Auto,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,8C6S86ESGC,19,37979,210682,541,109,14.11,12,Bachelor's,Full-time,Married,No,No,Other,0,0
255343,98R4KDHNND,32,51953,189899,511,14,11.55,24,High School,Part-time,Divorced,No,No,Home,1,0
255344,XQK1UUUNGP,56,84820,208294,597,70,5.29,60,High School,Self-employed,Married,Yes,Yes,Auto,0,0
255345,JAO28CPL4H,42,85109,60575,809,40,20.90,48,High School,Part-time,Single,Yes,Yes,Other,0,0
255346,ZTH91CGL0B,62,22418,18481,636,113,6.73,12,Bachelor's,Unemployed,Divorced,Yes,No,Education,0,0

In [4]:
X = data.drop('Default', axis=1)
X = X.drop ('UserID', axis=1)# Features
y = data['Default'] # labels

# Data Processing

In [5]:
# Apply Label Encoding to categorical columns
categorical_columns = ['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose','ZakatEligible']
label_encoder = LabelEncoder()
for column in categorical_columns:
    if X[column].dtype == 'object':  # Check if the column contains strings
        X[column] = label_encoder.fit_transform(X[column])

# Defining training and testing data

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Defining model

In [20]:
model = RandomForestClassifier(
    n_estimators=50,
    max_features="sqrt",
    min_samples_leaf=1,
    min_samples_split=2,
    bootstrap=True,
    random_state=42,
    n_jobs=-1
)

In [22]:
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50, n_jobs=-1, random_state=42)

In [30]:
y_pred = model.predict(X_test)
proba = model.predict_proba(X_test)


p_y1_pct = proba[:, 1] * 100                          # P(y=1) in %

results = pd.DataFrame({
    "y_pred": y_pred,
    "p_y1_%": np.round(p_y1_pct, 2)
})

print(results.head(20))

    y_pred  p_y1_%
0        0    16.0
1        0     2.0
2        0    14.0
3        0    30.0
4        0     6.0
5        0    28.0
6        0    24.0
7        0    40.0
8        0     2.0
9        0     8.0
10       0    14.0
11       0    12.0
12       0     8.0
13       0     0.0
14       0    16.0
15       0    10.0
16       0    10.0
17       1    52.0
18       0     4.0
19       0    18.0

In [31]:
defaulter = results[results['y_pred'] == 1]
defaulter.head()

     y_pred  p_y1_%
17        1    52.0
107       1    54.0
149       1    66.0
348       1    52.0
410       1    54.0